-- Code generated by dmarc-analyzer generate_sql. DO NOT EDIT.

CREATE TABLE aggregate_report_records (
    source_ip text,
    count bigint,
    disposition text,
    eval_dkim text,
    eval_spf text,
    header_from text,
    envelope_from text,
    envelope_to text,
    aggregate_report_id text NOT NULL,
    record_number bigint NOT NULL
);

CREATE TABLE aggregate_reports (
    message_id text NOT NULL,
    organization text,
    email text,
    extra_contact text,
    report_id text,
    date_range_begin bigint,
    date_range_end bigint,
    domain text,
    align_dkim text,
    align_spf text,
    policy text,
    subdomain_policy text,
    percentage bigint,
    failure_report text
);

CREATE TABLE dkim_auth_results (
    domain text NOT NULL,
    selector text,
    result text,
    human_result text,
    aggregate_report_id text NOT NULL,
    record_number bigint NOT NULL
);

CREATE TABLE dmarc_reporting_fulls (
    message_id text,
    record_number bigint,
    domain text,
    policy text,
    subdomain_policy text,
    align_dkim text,
    align_spf text,
    pct bigint,
    source_ip text,
    esp text,
    org_name text,
    org_id text,
    host_name text,
    domain_name text,
    host_name_matches_ip text,
    city text,
    state text,
    country text,
    longitude text,
    latitude text,
    reverse_lookup text[],
    message_count bigint,
    disposition text,
    eval_dkim text,
    eval_spf text,
    header_from text,
    envelope_from text,
    envelope_to text,
    auth_dkim_domain text[],
    auth_dkim_selector text[],
    auth_dkim_result text[],
    auth_spf_domain text[],
    auth_spf_scope text[],
    auth_spf_result text[],
    po_reason text[],
    po_comment text[],
    start_date bigint,
    end_date bigint,
    last_update text
);

CREATE TABLE po_reasons (
    reason text NOT NULL,
    comment text,
    aggregate_report_id text NOT NULL,
    record_number bigint NOT NULL
);

CREATE TABLE spf_auth_results (
    domain text NOT NULL,
    scope text,
    result text,
    aggregate_report_id text NOT NULL,
    record_number bigint NOT NULL
);

ALTER TABLE ONLY aggregate_report_records
    ADD CONSTRAINT aggregate_report_records_pkey PRIMARY KEY (aggregate_report_id, record_number);

ALTER TABLE ONLY aggregate_reports
    ADD CONSTRAINT aggregate_reports_pkey PRIMARY KEY (message_id);

ALTER TABLE ONLY dkim_auth_results
    ADD CONSTRAINT dkim_auth_results_pkey PRIMARY KEY (domain, aggregate_report_id, record_number);

ALTER TABLE ONLY po_reasons
    ADD CONSTRAINT po_reasons_pkey PRIMARY KEY (reason, aggregate_report_id, record_number);

ALTER TABLE ONLY spf_auth_results
    ADD CONSTRAINT spf_auth_results_pkey PRIMARY KEY (domain, aggregate_report_id, record_number);
