-- Code generated by dmarc-analyzer generate_sql. DO NOT EDIT.

CREATE TABLE aggregate_report_records (
    source_ip text,
    count bigint,
    disposition text,
    eval_dkim text,
    eval_spf text,
    header_from text,
    envelope_from text,
    envelope_to text,
    aggregate_report_id text,
    record_number bigint
);

CREATE TABLE aggregate_reports (
    message_id text NOT NULL,
    organization text,
    email text,
    extra_contact text,
    report_id text,
    date_range_begin bigint,
    date_range_end bigint,
    domain text,
    align_dkim text,
    align_spf text,
    policy text,
    subdomain_policy text,
    percentage bigint,
    failure_report text
);

CREATE TABLE dkim_auth_results (
    domain text,
    selector text,
    result text,
    human_result text,
    aggregate_report_id text,
    record_number bigint
);

CREATE TABLE po_reasons (
    reason text,
    comment text,
    aggregate_report_id text,
    record_number bigint
);

CREATE TABLE spf_auth_results (
    domain text,
    scope text,
    result text,
    aggregate_report_id text,
    record_number bigint
);

ALTER TABLE ONLY aggregate_reports
    ADD CONSTRAINT aggregate_reports_pkey PRIMARY KEY (message_id);
