/* tslint:disable */
/* eslint-disable */
/**
 * DMARC Analyzer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface DmarcChartDaily {
    'name'?: string;
    'series'?: Array<DmarcChartVolume>;
}
export interface DmarcChartResp {
    'chartdata': Array<DmarcChartDaily>;
    'domain': string;
}
export interface DmarcChartVolume {
    'name'?: number;
    'value'?: number;
}
export interface DmarcDetailResp {
    'detail_rows': Array<DmarcReportingDetail>;
}
export interface DmarcReportingDetail {
    'message_count'?: number;
    'report_org_name'?: string;
    'source_ip'?: string;
    'esp'?: string;
    'source_domain'?: string;
    'source_host'?: string;
    'reverse_lookup'?: Array<string>;
    'country'?: string;
    'disposition'?: string;
    'eval_dkim'?: string;
    'eval_spf'?: string;
    'header_from'?: string;
    'envelope_from'?: string;
    'envelope_to'?: string;
    'auth_dkim_domain'?: Array<string>;
    'auth_dkim_selector'?: Array<string>;
    'auth_dkim_result'?: Array<string>;
    'auth_spf_domain'?: Array<string>;
    'auth_spf_scope'?: Array<string>;
    'auth_spf_result'?: Array<string>;
    'po_reason'?: Array<string>;
    'po_comment'?: Array<string>;
}
export interface DmarcReportingSummary {
    'source'?: string;
    'total_count'?: number;
    'pass_count'?: number;
    'spf_aligned_count'?: number;
    'dkim_aligned_count'?: number;
    'fully_aligned_count'?: number;
    'source_type'?: string;
}
export interface DomainStat {
    'domain': string;
    'total_count': number;
    'pass_count': number;
}
export interface DomainSummaryCounts {
    'total_count'?: number;
    'pass_count'?: number;
    'spf_aligned_count'?: number;
    'dkim_aligned_count'?: number;
    'fully_aligned_count'?: number;
    'message_count'?: number;
}
export interface DomainSummaryResp {
    'summary': Array<DmarcReportingSummary>;
    'domain_summary_counts': DomainSummaryCounts;
    'start_date': string;
    'end_date': string;
    'domain': string;
}

/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary DMARC chart data
         * @param {string} domain 
         * @param {string} [start] RFC3339 timestamp
         * @param {string} [end] RFC3339 timestamp
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        handleDmarcChart: async (domain: string, start?: string, end?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'domain' is not null or undefined
            assertParamExists('handleDmarcChart', 'domain', domain)
            const localVarPath = `/api/domains/{domain}/chart/dmarc`
                .replace(`{${"domain"}}`, encodeURIComponent(String(domain)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (start !== undefined) {
                localVarQueryParameter['start'] = start;
            }

            if (end !== undefined) {
                localVarQueryParameter['end'] = end;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Domain detail report
         * @param {string} domain 
         * @param {string} [start] RFC3339 timestamp
         * @param {string} [end] RFC3339 timestamp
         * @param {string} [source] 
         * @param {string} [sourceType] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        handleDmarcDetail: async (domain: string, start?: string, end?: string, source?: string, sourceType?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'domain' is not null or undefined
            assertParamExists('handleDmarcDetail', 'domain', domain)
            const localVarPath = `/api/domains/{domain}/report/detail`
                .replace(`{${"domain"}}`, encodeURIComponent(String(domain)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (start !== undefined) {
                localVarQueryParameter['start'] = start;
            }

            if (end !== undefined) {
                localVarQueryParameter['end'] = end;
            }

            if (source !== undefined) {
                localVarQueryParameter['source'] = source;
            }

            if (sourceType !== undefined) {
                localVarQueryParameter['source_type'] = sourceType;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List domains with recent stats
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        handleDomainList: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/domains`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Domain summary report
         * @param {string} domain 
         * @param {string} [start] RFC3339 timestamp
         * @param {string} [end] RFC3339 timestamp
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        handleDomainSummary: async (domain: string, start?: string, end?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'domain' is not null or undefined
            assertParamExists('handleDomainSummary', 'domain', domain)
            const localVarPath = `/api/domains/{domain}/report`
                .replace(`{${"domain"}}`, encodeURIComponent(String(domain)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (start !== undefined) {
                localVarQueryParameter['start'] = start;
            }

            if (end !== undefined) {
                localVarQueryParameter['end'] = end;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary DMARC chart data
         * @param {string} domain 
         * @param {string} [start] RFC3339 timestamp
         * @param {string} [end] RFC3339 timestamp
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async handleDmarcChart(domain: string, start?: string, end?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DmarcChartResp>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.handleDmarcChart(domain, start, end, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.handleDmarcChart']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Domain detail report
         * @param {string} domain 
         * @param {string} [start] RFC3339 timestamp
         * @param {string} [end] RFC3339 timestamp
         * @param {string} [source] 
         * @param {string} [sourceType] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async handleDmarcDetail(domain: string, start?: string, end?: string, source?: string, sourceType?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DmarcDetailResp>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.handleDmarcDetail(domain, start, end, source, sourceType, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.handleDmarcDetail']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List domains with recent stats
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async handleDomainList(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<DomainStat>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.handleDomainList(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.handleDomainList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Domain summary report
         * @param {string} domain 
         * @param {string} [start] RFC3339 timestamp
         * @param {string} [end] RFC3339 timestamp
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async handleDomainSummary(domain: string, start?: string, end?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DomainSummaryResp>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.handleDomainSummary(domain, start, end, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.handleDomainSummary']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary DMARC chart data
         * @param {string} domain 
         * @param {string} [start] RFC3339 timestamp
         * @param {string} [end] RFC3339 timestamp
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        handleDmarcChart(domain: string, start?: string, end?: string, options?: RawAxiosRequestConfig): AxiosPromise<DmarcChartResp> {
            return localVarFp.handleDmarcChart(domain, start, end, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Domain detail report
         * @param {string} domain 
         * @param {string} [start] RFC3339 timestamp
         * @param {string} [end] RFC3339 timestamp
         * @param {string} [source] 
         * @param {string} [sourceType] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        handleDmarcDetail(domain: string, start?: string, end?: string, source?: string, sourceType?: string, options?: RawAxiosRequestConfig): AxiosPromise<DmarcDetailResp> {
            return localVarFp.handleDmarcDetail(domain, start, end, source, sourceType, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List domains with recent stats
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        handleDomainList(options?: RawAxiosRequestConfig): AxiosPromise<Array<DomainStat>> {
            return localVarFp.handleDomainList(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Domain summary report
         * @param {string} domain 
         * @param {string} [start] RFC3339 timestamp
         * @param {string} [end] RFC3339 timestamp
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        handleDomainSummary(domain: string, start?: string, end?: string, options?: RawAxiosRequestConfig): AxiosPromise<DomainSummaryResp> {
            return localVarFp.handleDomainSummary(domain, start, end, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary DMARC chart data
     * @param {string} domain 
     * @param {string} [start] RFC3339 timestamp
     * @param {string} [end] RFC3339 timestamp
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public handleDmarcChart(domain: string, start?: string, end?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).handleDmarcChart(domain, start, end, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Domain detail report
     * @param {string} domain 
     * @param {string} [start] RFC3339 timestamp
     * @param {string} [end] RFC3339 timestamp
     * @param {string} [source] 
     * @param {string} [sourceType] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public handleDmarcDetail(domain: string, start?: string, end?: string, source?: string, sourceType?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).handleDmarcDetail(domain, start, end, source, sourceType, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List domains with recent stats
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public handleDomainList(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).handleDomainList(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Domain summary report
     * @param {string} domain 
     * @param {string} [start] RFC3339 timestamp
     * @param {string} [end] RFC3339 timestamp
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public handleDomainSummary(domain: string, start?: string, end?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).handleDomainSummary(domain, start, end, options).then((request) => request(this.axios, this.basePath));
    }
}



