/*
 * DMARC Analyzer API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

// Code generated by openapi-generator from api/openapi.json. DO NOT EDIT.

package handler

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

type RouteDefinition struct {
	Method  string
	Path    string
	Handler gin.HandlerFunc
}

var Routes = []RouteDefinition{

	{Method: http.MethodGet, Path: "/api/domains/:domain/chart/dmarc", Handler: HandleDmarcChartFromOpenAPI},

	{Method: http.MethodGet, Path: "/api/domains/:domain/report/detail", Handler: HandleDmarcDetailFromOpenAPI},

	{Method: http.MethodGet, Path: "/api/domains", Handler: HandleDomainListFromOpenAPI},

	{Method: http.MethodGet, Path: "/api/domains/:domain/report", Handler: HandleDomainSummaryFromOpenAPI},
}

func RegisterRoutes(router *gin.Engine) {
	for _, route := range Routes {
		router.Handle(route.Method, route.Path, route.Handler)
	}
}
